// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtoyrUVzqlkoj6xjKWN-xHl9rMfo4mviA',
    appId: '1:377376525654:web:eb328fa11a6e1473201af7',
    messagingSenderId: '377376525654',
    projectId: 'my-money-tracker-c4411',
    authDomain: 'my-money-tracker-c4411.firebaseapp.com',
    storageBucket: 'my-money-tracker-c4411.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-HUNHHaD0dQ4JmNgYVAdZ3HUtNLfzmLg',
    appId: '1:377376525654:android:7b8ae0bb9ac1e3f7201af7',
    messagingSenderId: '377376525654',
    projectId: 'my-money-tracker-c4411',
    storageBucket: 'my-money-tracker-c4411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1rCJMMnYA511-u1Rcn3TmowElnHPyOo',
    appId: '1:377376525654:ios:62eb3afc60757398201af7',
    messagingSenderId: '377376525654',
    projectId: 'my-money-tracker-c4411',
    storageBucket: 'my-money-tracker-c4411.appspot.com',
    iosClientId: '377376525654-rhb36onrln3u2eb8qo621sfui31l7gjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY1rCJMMnYA511-u1Rcn3TmowElnHPyOo',
    appId: '1:377376525654:ios:62eb3afc60757398201af7',
    messagingSenderId: '377376525654',
    projectId: 'my-money-tracker-c4411',
    storageBucket: 'my-money-tracker-c4411.appspot.com',
    iosClientId: '377376525654-rhb36onrln3u2eb8qo621sfui31l7gjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTracker',
  );
}
